(component
  (type $empty (;0;) (func))
  (type $i (;1;)
    (instance)
  )
  (type (;2;)
    (component
      (core type (;0;)
        (module
          (type (;0;) (func))
          (import "" "a" (func (type 0)))
          (type (;1;) (func (param i32)))
          (import "" "b" (func (type 1)))
          (export "a" (func (type 0)))
          (type (;2;) (func (param i32)))
          (export "b" (func (type 2)))
        )
      )
      (import "l" (core module (;0;) (type 0)))
    )
  )
)
